### PR TITLE
Package rmview

### PR DESCRIPTION
**Pull request by ChrisPattison**
This packages rmview. An example installation & usage with a remarkable already setup is below.

Ideally there would be a command included in the package to install the binaries on the remarkable so that an install&run flow would be `pip install rmview` `rmview_rm_install` `rmview`

Screen Shot 2020-08-06 at 6 34 33 PM

### CODE REVIEW

**Comment by ChrisPattison** [comment]
As an aside, it wouldn't be a bad idea to search ~./rmview for a configure file

**Comment by bordaigorl** [comment]
Thank you for this!
I will have a look and merge soon.
I want to improve the readme and the configuration system a little anyway.
The config should be probably first searched in the standard paths of the host OS...

**Review by bordaigorl — DISMISSED** [review]

**Review by bordaigorl — COMMENTED** [review]
I tried running `pip install .`, it runs fine but then I get an exception on run:

```
from . import resources 
ImportError: attempted relative import with no known parent package
```

**Comment by bordaigorl** [comment]
My bad, made a mistake. Works fine, ready to merge

**Review by bordaigorl — APPROVED** [review]

**Pull request merged**
