### PR TITLE
support rm's 2.9 vnc server

### PR DESCRIPTION
**Pull request by ddvk**
here are the changes needed to get the 2.9 share working.

there are some things missing:
broadcast detection and like correct challenge calculation

### CODE REVIEW

**Comment by macoj** [comment]
I couldn't make it work; still having `twisted.internet.error.ConnectionRefusedError` when try to connect. 

I am on 2.9.0.153. 

By the way, this patch required me to `pip3 install pyOpenSSL`.

**Comment by ddvk** [comment]
you have to start the sharing on the tablet

**Comment by macoj** [comment]
Great. It works now!

**Comment by rottweilertje** [comment]
> you have to start the sharing on the tablet

Do you mean by using the buildin `Present with Screen Share` option?
I'm on 2.9.0.210 the option to start sharing is disabled if you are not logged on to your cloud account.

I'm not on the beta program and got it pushed today.

**Comment by delaere** [comment]
Hi, I have a rM1 running 2.9.0.210 since yesterday. rmView is running fine with the patch and the native ScreenShare feature activated.

**Comment by bordaigorl** [comment]
@ddvk is there any way to circumvent the need for a cloud account?
Is there any way (better if programmatic) to force the server to start?
(my hopes are not high since it looks like they embedded it into xochitl...)

**Comment by andresakle** [comment]
@delaere What patch are you referring to? I have tried to run rmView with the native ScreenShare function and get the following message: 
```
Connecting...
Connected to 192.168.1.14
peek: Input/output error

Starting VNC server
```
The screen remains white.

**Comment by delaere** [comment]
@andresakle : I just mean using the branch proposed in this PR (ddvk:vnc29).
I had an existing clone of the base repo (vnc branch), so I simply did the following in the existing directory:
```
git pull
git remote add fork1 https://github.com/ddvk/rmview.git
git pull fork1 vnc29
pip install .
```

Then, you need to start the ScreenShare on the reMarkable before rmview, which require a cloud connection, as discussed above.

The behavior of the share slightly differs from the native VNC implementation in that you can only share documents. The system will not update the display if you navigate in between documents or open the settings page. I sort of like it (I use to share the rmview windows for teaching purposes and students don't have to see the list of docs if I realize that I have to navigate to another document during the lesson).

**Comment by seanelvidge** [comment]
Hi all,

I have rmview installed from ddvk:vnc29 on Ubuntu 20.04.01 and am running a rM2 with software 2.9.1.217. 

Starting ScreenShare first and then opening rmview I can connect to the tablet and then get the white screen load. As I write on the rM I can see the red "marker" for where I am writing shows on my desktop, but no writing then actually appears on the desktop and just remains white (sounds like a similar issue to @andresakle).

Looking at the rmview output there is an error after it confirms the connection to the rM, specifically "peek: Input/output error".

Strongly appreciate any help anyone can provide, meant to be giving a seminar on Zoom tomorrow and can no longer connect (I had auto-updates turned on, which has now been "fixed" (turned off) to avoid this issue in the future!).

**Comment by gustaphe** [comment]
Works flawlessly for me.

A note for Arch users: editing the `PKGBUILD` of `aur/rmview-git` to have 
```
source=("${pkgname}"::'git+https://github.com/ddvk/rmview.git#branch=vnc29')
```
does it.

**Comment by yujikiriki** [comment]
hey @gustaphe, when you write "flawlessly" is using the new ScreenShare functionality or using the `rM2-vnc-server-standalone`?

**Comment by gustaphe** [comment]
ScreenShare.

**Comment by bordaigorl** [comment]
I incorporated this PR in the now merged devel branch, which now supports both the old server and the new ScreenShare.
If I have time I will even add the reStreamer-style method as a backend so that if something breaks one has a failsafe (although that method broke in the past too).

Thanks @ddvk so much for your contribution!

**Pull request closed without merging**
