### PR TITLE
add binary release workflow

### PR DESCRIPTION
**Pull request by ddvk**
adds a workflow to create a windows binary
the problem was the missing `C:\Users\\AppData\Local\rmview` folder

### CODE REVIEW

**Comment by bordaigorl** [comment]
Thank you @ddvk!
I'd like to include a macos app bundle too, but I am new to GitHub workflows.
Do you happen to know how to do that? If not I can work it out but it will have to wait until I can read up about it.
How can one test workflows on the cloud?

**Comment by ddvk** [comment]
i think i can add the mac build as well, but i couldnt test the package  (i have a very old macbook pro)

**Comment by bordaigorl** [comment]
I can test it :)
How does one run these workflows on the cloud just for testing?

**Comment by ddvk** [comment]
i'm still learning as well

**Comment by psykzz** [comment]
@bordaigorl / @ddvk you can test workflows locally with [act](https://github.com/nektos/act)

**Comment by bordaigorl** [comment]
@psykzz thanks for the input.
I saw `act` but the readme says:

> Windows and macOS based platforms are currently unsupported and won't work

which makes it useless since the windows and macos bundles are exactly those that I would aim to provide...

**Comment by psykzz** [comment]
My mistake, you're totally right. I know some work is being done and requests have been made to just run outside of a container but i dont believe the author want's to go down that route from what i can see.

**Pull request merged**
